#!/bin/sh
#script to start expressjs with some env variables ( defined in .nodexenv )
if [ -e $(pwd)/.nodexenv ]; then
  . $(pwd)/.nodexenv
fi

#all these can be set in .nodexenv
export DB_URL

node=$(which node)

if [ -n "$1" ]; then
  $node debug app.js
else
  $node app.js
fi
